---
# 10.system_user.yml - create Hotrod group and system user

- name: "[system_user] create Hotrod group"
  when:
    - "hotrod_system_group !== 'root'"
  group:
    name: "{{ hotrod_system_group }}"
    state: present


- name: "[system_user] create Hotrod user"
  when:
    - "hotrod_system_user !== 'root'"
  user:
    name: "{{ hotrod_system_user }}"
    comment: "Hotrod system user"
    group: "{{ hotrod_system_group }}"
    system: yes