---
# 93.remove_user.yml - remove Hotrod group and system user

- name: "[system_user] remove Hotrod user"
  when:
    - hotrod_system_user == "hotrod"
  user:
    name: "{{ hotrod_system_user }}"
    state: absent

- name: "[system_user] remove Hotrod group"
  when:
    - hotrod_system_group == "hotrod"
  group:
    name: "{{ hotrod_system_group }}"
    state: absent
