---
- name: Install Hotrod server
  hosts: localhost
  roles:
    - hotrod
  vars:
    # control
    hotrod_download_uri: "<specify target URI>"
    hotrod_download_uri_sha1: "{{ hotrod_download_uri }}.sha1"
    hotrod_system_user: hotrod
    hotrod_system_group: hotrod

    # binary
    hotrod_install_binary: yes
    hotrod_binary_install_directory: /opt/hotrod
    hotrod_binary_install_path: "{{ hotrod_binary_install_directory }}/hotrod"
    hotrod_binary_system_path: /usr/bin/hotrod

    # server
    hotrod_install_server: yes
    hotrod_server_admin_init_password: "VerySecretSecret"
    hotrod_server_staging_dir: /var/lib/hotrod-server
    hotrod_server_bind_address: 127.0.0.1:3000
    hotrod_server_log_retention_days: 30
    hotrod_server_enable_server_agent: yes
    hotrod_server_auto_enrollment_key: "anotherVerySecretSecret"
    hotrod_server_systemd_unit_name: hotrod-server.service
    hotrod_server_systemd_unit_path: /lib/systemd/system/{{ hotrod_server_systemd_unit_name }}